### ISSUE TITLE
Yarn start fails: grunt missing

### ISSUE THREAD

**Issue by ikkemaniac** [portainer/dev-toolkit#1]
I'm trying to get this toolkit up and running. I'm a little confused how to get the actual dev environment to build/run the code but figured it should be possible using the terminal in vscode server.

with both ```portainer/dev-toolkit:2020.11``` and  ```portainer/dev-toolkit:2022.01```
Running ```yarn``` results in:
```
root@8f6ebf88f40f:~/portainer# yarn
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "@uirouter/angularjs@1.0.11" is incompatible with requested version "@uirouter/angularjs@1.0.29"
[3/5] Fetching packages...
[######-------------------------------------------------------------------------------------------------------------------------------------] 103/2449^C
```
running ```yarn start``` gives:
```
root@8f6ebf88f40f:~/portainer# yarn start
yarn run v1.22.17
$ grunt start
/bin/sh: 1: grunt: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It's my first time playing around openvscode-server or a similar toolkit, maybe I'm just missing something?

Please advice, thanks!

---

edit: Looks like ```yarn start:toolkit``` in the vscode terminal does the trick! Maybe it's good to add this explanation to the README?

**Comment by deviantony** [comment]
Heyo @ikkemaniac, this toolkit is currently used by me mostly and is not officially supported by Portainer (as such, instructions found otherwise online regarding how to develop against Portainer might not work).

I've added the `yarn start:toolkit` to do the equivalent of `yarn start`, however I'm not using it.

I mostly use the following commands after starting the toolkit (inside the toolkit):

```
> yarn // to install the dependencies
> yarn build:server // to build the backend
> yarn build:client // to build the frontend
> cd dist && ./portainer --data /tmp/portainer // to run a dev Portainer instance
```

**Comment by ikkemaniac** [comment]
10-4

I was expecting the dependencies to be persistent so that threw me off with just ```yarn```.
Anyway, neat setup - hope you'll keep it public :)

**Comment by deviantony** [comment]
@ikkemaniac

Yes I'm still enhancing it at the moment :)

Dependencies should be persisted though, what was wrong with that?

**Comment by deviantony** [comment]
Closing this issue, feel free to continue the discussion in here if you need help.
